// Generated by CoffeeScript 1.6.3
var ClientSide, ThousandQueries, ThousandResponse;

ClientSide = (function() {
  function ClientSide(doc) {
    this.doc = $(doc);
  }

  ClientSide.prototype.activateDates = function(cn) {
    var ad, _i, _len, _ref, _results;
    _ref = $("." + cn, this.doc);
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      ad = _ref[_i];
      _results.push($(ad).datepicker({
        dateFormat: 'dd/mm/yy'
      }));
    }
    return _results;
  };

  return ClientSide;

})();

ThousandQueries = (function() {
  function ThousandQueries(reqdata) {
    this.reqdata = reqdata;
  }

  ThousandQueries.prototype.makeReq = function(rid, cb) {
    var dest, lxn, us;
    lxn = document.location.toString().replace(/\/dashboards\//, '/json/');
    dest = "" + lxn + ".json";
    console.log("Request to: " + dest);
    us = this;
    return $.ajax(dest, {
      data: {
        reqid: rid
      },
      success: (function(dat, stt, req) {
        return cb(new ThousandResponse(dat));
      })
    });
  };

  return ThousandQueries;

})();

ThousandResponse = (function() {
  function ThousandResponse(respdata) {
    this.respdata = respdata;
  }

  ThousandResponse.prototype.lmps = function(them) {
    return this.respdata.lmps || this.respdata.resp || them;
  };

  ThousandResponse.prototype.average = function() {
    return this.respdata.avg;
  };

  ThousandResponse.prototype.fetch = function(them) {
    return this.respdata.resp || them;
  };

  return ThousandResponse;

})();
